version: "3"
services:

  # Container used for deploying the API
  api:
    build: .
    ports:
      - 8808:8808
    volumes:
      - ./:/app
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'
      LOG_LEVEL: 'INFO'
    entrypoint: uvicorn trapi.main:app --host 0.0.0.0 --port 8808 --reload

  # Container used for testing and running scripts
  tests:
    build: .
    volumes:
      - ./:/app
      - ~/.nanopub-docker:/root/.nanopub
    environment:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'
      LOG_LEVEL: 'INFO'
    # entrypoint: pytest --cov=src tests/integration
    entrypoint:  pytest tests/integration/test_openpredict_api.py
    # entrypoint:  pytest tests/integration/test_openpredict_api.py::test_post_trapi -s
    # entrypoint:  pytest tests/package/test_decorator.py -s

  # Container to deploy a JupyterLab/VSCode workspace for development
  workspace:
    image: ghcr.io/maastrichtu-ids/jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work
    user: root
    environment:
      - GRANT_SUDO=yes
      - LOG_LEVEL=INFO
      ## With password:
      # - JUPYTER_TOKEN=password
