version: "3"
services:

  # Container used for deploying the API
  api:
    build: .
    ports:
      - 8808:8808
    volumes:
      - ./:/app
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: 'INFO'
      NO_JAEGER: "true"
    
