site_name: TRAPI Predict Kit
site_description: A python package that helps data scientists to build, and publish prediction models in a FAIR and reproducible manner. It helps to deploy API endpoints for retrieving predictions, which comply with the NCATS Biomedical Data Translator standards (Translator Reasoner API and BioLink model)
site_author: Vincent Emonet
site_url: https://maastrichtu-ids.github.io/trapi-predict-kit
repo_name: MaastrichtU-IDS/trapi-predict-kit
repo_url: https://github.com/MaastrichtU-IDS/trapi-predict-kit
edit_uri: "edit/master/docs/"
copyright: Copyright &copy; 2023 Vincent Emonet

nav:
  - Getting started:
    - Getting started: index.md
    - Creating a project: getting-started/create-project.md
    - Exposing a prediction model: getting-started/expose-model.md
    - Saving a model: getting-started/save-model.md
    # - Development: getting-started/development.md

  - OpenPredict API:
    - Introduction: openpredict-api/introduction.md
    - Deploying locally: openpredict-api/deploy.md

  # - Code Reference:
  #   - TRAPI: reference/trapi.md

  - "<span>Issues&nbsp;&nbsp;<i class='fa-solid fa-arrow-up-right-from-square'></i></span>": https://github.com/MaastrichtU-IDS/trapi-predict-kit/issues" target="_blank
# Icons: https://fontawesome.com/icons and https://squidfunk.github.io/mkdocs-material/reference/icons-emojis


theme:
  name: "material"
  favicon: assets/icon.png
  logo: assets/icon.png
  # icon:
  #   logo: material/microscope
  language: en
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.instant
    # - navigation.tabs.sticky


plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: true

watch:
  - src
  - docs


# Styled blocks: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - smarty


extra_css:
  - assets/custom.css

extra_javascript:
  - assets/fontawesome.min.js
  - assets/solid.min.js

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/trapi-predict-kit
    - icon: fontawesome/brands/github
      link: https://github.com/MaastrichtU-IDS
    # - icon: fontawesome/brands/docker
    #   link: https://github.com/orgs/MaastrichtU-IDS/packages
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/
