name: Publish package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  tests:
    uses: MaastrichtU-IDS/translator-openpredict/.github/workflows/test-package.yml@master
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install build

    - name: Build package
      working-directory: trapi-predict-kit
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        packages-dir: trapi-predict-kit/dist/
